@startuml
west -> west:connection_accepted
activate request_handler
west -> request_handler:finalize_state(request_header)
return validation_result
alt header accepted
	loop while data available and operation succeeded
		west -> request_handler:process_request_body(current buffer)
		return write_result
	end
	west -> request_handler:finalize_state([inout] field_map)
	return validation_result
	opt request not accepted
		west -> west:stop_reading(socket)
	end
else
	west -> west:stop_reading(socket)
	west -> request_handler:finalize_state([inout] field_map, finalize_state_result)
	return
end
loop while data available and operation succeeded
	west -> request_handler:read_response_content([out] current buffer)
	return read_result
end
west -> west:connection_closed
destroy request_handler
@enduml